### ISSUE TITLE
ModuleNotFoundError: No module named 'skrl.envs.wrappers'

### ISSUE THREAD

**Issue by sesem738** [Toni-SM/skrl#110]
Hello, 

I tried running on of the examples of Isaac Gym and I receive this error. from skrl.envs.wrappers.torch import wrap_envModuleNotFoundError: No module named 'skrl.envs.wrappers'. I check the repo and it looks like wrap_env doesn't exist there anymore.

**Comment by Toni-SM** [comment]
Hi @sesem738 

Using `from skrl.envs.wrappers.torch import wrap_env` or `from skrl.envs.wrappers.jax import wrap_env` is only available in `skrl>=1.0.0rc2`. (https://github.com/Toni-SM/skrl/blob/main/CHANGELOG.md#100-rc2---2023-08-11)

You can install this pre-release version using the following command.

```bash
pip install --pre skrl==1.0.0rc2
```

I am planning to release `v1.0.0` today
