### ISSUE TITLE
Getting blank stderr while training with OIGE

### ISSUE THREAD

**Issue by Pipe-Runner** [Toni-SM/skrl#133]
### Description

I get duplicate progress bars from stderr. This code used to work perfectly fine in the previous version of OIGE. I have upgraded to 2023.1.0 yesterday. I have been getting this behavior since then.

![image](https://github.com/Toni-SM/skrl/assets/19551058/95dc4c60-c911-4d86-8ee5-42902ee87873)
The training seems to work correctly though. No error and the policy is trained as expected. 

I do get this before the training starts though. Not sure if this is related to the problem.
![image](https://github.com/Toni-SM/skrl/assets/19551058/7090d248-304b-4766-a4de-c49b64ee7fd4)

### What skrl version are you using?

1.0.0

### What ML framework/library version are you using?

PyTorch Version: 2.0.1, OIGE 2023.1.0a0 

### Additional system information

Linux (Ubuntu 22.04)

**Comment by Toni-SM** [comment]
Hi @Pipe-Runner 

Thanks for reporting this issue.
I have changed (in the `develop` branch, to be released soon) the output of the progress messages (generated with `tdqm`) to `sys.stdout` (tqdm default sys.stderr) so Isaac Sim will not show duplicated message anymore.


https://github.com/Toni-SM/skrl/blob/7b090a1674b3ff1240a49385bd7fd757571f7145/skrl/trainers/torch/base.py#L165

https://github.com/Toni-SM/skrl/blob/bb493a5c8e9ad71c0412d46df38802038ede4c86/skrl/trainers/torch/base.py#L166
