### ISSUE TITLE
Is there a way to automatically save the best result along with the checkpoints?

### ISSUE THREAD

**Issue by famora2** [Toni-SM/skrl#14]
Hi @Toni-SM ,

![Screenshot from 2022-05-24 10-36-00](https://user-images.githubusercontent.com/53815515/169987903-b25e6a74-f7d3-4c5b-99cc-2b8bd0828b4c.png)

Above you can see the training result of FrankaReach task. As you can see the reward drops after a certain step. But as the best result from the beginning is not automatically saved, one has to check the tensorboard and select the appropriate checkpoint from the logs. Is there a way to automatically save the best result along with the checkpoints like in ISAAC GYM?

**Comment by Toni-SM** [comment]
Hi @Joo236 

Yeah, this is a good idea... I will try to implement it for the next patch

**Comment by Joo236** [comment]
The code gives following error:   
```
File "/home/user/skrl/skrl/agents/torch/base.py", line 163, in write_checkpoint
    state_dict=self.checkpoint_best_models["models"][k])
TypeError: save() got an unexpected keyword argument 'state_dict'
```

**Comment by Toni-SM** [comment]
Hi @famora2 

Are you using the `develop` branch? Is it updated?

You can do it by executing the following commands inside the skrl repository's root directory 

```bash
git checkout develop
git pull --all
```

Also, you can check if the `save` method is updated (`skrl/models/torch/base.py` file)

https://github.com/Toni-SM/skrl/blob/cd45cf9d651c39ae4816145ff02f974825131410/skrl/models/torch/base.py#L285-L294
