### ISSUE TITLE
No module named omni.isaac.contrib_envs and  omni.isaac.orbit_envs

### ISSUE THREAD

**Issue by mrsbCN** [Toni-SM/skrl#145]
### Description

I am using the latest [orbit](https://github.com/NVIDIA-Omniverse/orbit/tree/83e14f096ed3b20223cdca3065975bcc7dfa22f1) with skrl1.1.0. And I am trying to run example codes provide in you docs(like [torch_ant_ppo.py](https://skrl.readthedocs.io/en/latest/_downloads/3faa6f6c7e33a77373e38111c8999c22/torch_ant_ppo.py) ), But I got No module named omni.isaac.contrib_envs. After
search the commit on orbit, I find that they have [Renames Gym Envs related extensions to Tasks ](https://github.com/NVIDIA-Omniverse/orbit/tree/3149af0006d49e3e4bacc932ab4ef76e2a2e1ec8). So maybe we should also use this under load_isaac_orbit_env. Or even change the function name?
```
   # import orbit extensions
    import omni.isaac.contrib_tasks  # type: ignore
    import omni.isaac.orbit_tasks  # type: ignore
    from omni.isaac.orbit_tasks.utils import parse_env_cfg  # type: ignore
```

### What skrl version are you using?

1.0.0

### What ML framework/library version are you using?

pytorch 2.0.1

### Additional system information

3.10.14

**Comment by Toni-SM** [comment]
Hi @mrsbCN 

Now that Orbit has been unified with OIGE in Isaac Lab and skrl 1.2.0 has been released, this bug no longer exists.
