### ISSUE TITLE
Failing to wrap Isaac Gym Preview 4 Environments if No Wrapper Type is Given

### ISSUE THREAD

**Issue by ErcBunny** [Toni-SM/skrl#170]
### Description

When running the getting started tutorial:
```python
import isaacgymenvs

# import the environment wrapper
from skrl.envs.wrappers.torch import wrap_env

# create/load the environment using the easy-to-use API from NVIDIA
env = isaacgymenvs.make(seed=0,
                        task="Cartpole",
                        num_envs=512,
                        sim_device="cuda:0",
                        rl_device="cuda:0",
                        graphics_device_id=0,
                        headless=False)

# wrap the environment
env = wrap_env(env)  # or 'env = wrap_env(env, wrapper="isaacgym-preview4")'
```

`env = wrap_env(env)` does not work by default.

### What skrl version are you using?

1.2.0

### What ML framework/library version are you using?

PyTorch (2.3.1+cu121)

### Additional system information

Python 3.8.19 on Linux

**Comment by Toni-SM** [comment]
Hi @ErcBunny 

Fixed in branch `toni/update_wrappers` to be merge in develop soon

https://github.com/Toni-SM/skrl/blob/d2edbcf0d73b1533a382bb8560869bd1e05f286d/skrl/envs/wrappers/torch/__init__.py#L94-L95

**Comment by Toni-SM** [comment]
Solved in https://github.com/Toni-SM/skrl/releases/tag/1.3.0
