### ISSUE TITLE
Documentation -> WrapperTag: "isaaclab" is wrong, write "isaac-orbit" instead

### ISSUE THREAD

**Issue by PietroDrd** [Toni-SM/skrl#175]
### Description

In the Documentation at [Wrapping-API](https://skrl.readthedocs.io/en/latest/api/envs/wrapping.html#api-pytorch) both for pytorch and jax in the documentation file is indicated the wrapper tag: "isaaclab"

instead looking in the code it is used "isaac-orbit" (it works)

here a snap of the error occurred 
![image](https://github.com/user-attachments/assets/ce344abb-5657-4acc-8a68-b3e894f1f35a)

### What skrl version are you using?

1.1.0

### What ML framework/library version are you using?

Pytorch Version: 2.2.2+cu118, Pip 24.0,  conda 24.5.0, Isaaclab 4.0.0

**Comment by Toni-SM** [comment]
Hi @PietroDrd 

Starting with `skrl-v1.2.0` the `isaac-orbit` wrapper type was changed to `isaaclab`. 
This change was reflected in Isaac Lab last [2024-06-26](https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab_tasks/docs/CHANGELOG.rst#078-2024-06-26).

Also, please use the docs version 1.1.0 (https://skrl.readthedocs.io/en/1.1.0) for `skrl-v1.1.0`:
- https://skrl.readthedocs.io/en/1.1.0/api/envs/wrapping.html#skrl.envs.wrappers.torch.wrap_env
