### ISSUE TITLE
Unknown wrapper typew when using IsaacGymEnvs

### ISSUE THREAD

**Issue by Panda-Shawn** [Toni-SM/skrl#190]
### Description

When I run the example files provided by the [official document] (https://skrl.readthedocs.io/en/latest/intro/examples.html#:~:text=py%0Atorch_bidexhands_shadow_hand_over_mappo.py-,NVIDIA%20Isaac%20Gym%20preview,-%C2%B6), a value error comes as follows.

```
Traceback (most recent call last):
  File "skrl/example_ant.py", line 60, in <module>
    env = wrap_env(env)
  File "/home/lzixuan/miniconda3/envs/dexgrasp/lib/python3.8/site-packages/skrl/envs/wrappers/torch/__init__.py", line 154, in wrap_env
    raise ValueError(f"Unknown wrapper type: {wrapper}")
ValueError: Unknown wrapper type: ['isaacgymenvs.tasks.base.vec_task.VecTask']
Segmentation fault (core dumped)
```

### What skrl version are you using?

1.2.0

### What ML framework/library version are you using?

PyTorch

### Additional system information

Python 3.8, Ubuntu 20.04.6

**Comment by Toni-SM** [comment]
Hi @Panda-Shawn 

This issue is solved in a separate branch as indicated in https://github.com/Toni-SM/skrl/issues/170#issuecomment-2269578196

**Comment by Toni-SM** [comment]
Solved in https://github.com/Toni-SM/skrl/releases/tag/1.3.0
