### ISSUE TITLE
The demo of AnymalTerrain had bad result in skrl

### ISSUE THREAD

**Issue by Wjzsearcher** [Toni-SM/skrl#30]
Hi! Thanks for this wonderful library.
I found bad result with AnymalTerrain in skrl. The ppo of rl_games could get a useful policy after 1500 iterations(36000 timesteps), but for ppo in skrl(same hyper parameters, task file and timesteps), the result was so bad with low reward. 
I'm quite confused for the result.

**Comment by Toni-SM** [comment]
Hi @Wjzsearcher 

Many thanks for the report and sorry for the confusion. 
The problem behind that is the difference between the initialization of the model parameters in the current skrl examples with respect to rl_games.

rl_games's model does not assign initial values for the model's parameters and keeps the sigma (log_std in skrl) in zero.

```yaml
mu_init:
  name: default
sigma_init:
  name: const_initializer
  val: 0. # std = 1.
fixed_sigma: True

initializer:
  name: default
```

Then, by removing (comment) the model initialization in the skrl example it is possible can get similar performance as follow:
I am in process of updating the examples prior to the next release...

```python
# # Initialize the models' parameters (weights and biases) using a Gaussian distribution
# for model in models_ppo.values():
#     model.init_parameters(method_name="normal_", mean=0.0, std=0.1)   
```

Legend:
-  skrl (Gaussian model in v0.8.0): blue
- skrl (Multivariate Gaussian model in v0.8.0): red
- rl_games: orange

![Screenshot from 2022-09-21 18-03-26](https://user-images.githubusercontent.com/22400377/191557474-61d1c482-6302-43f2-8806-332cfaf12f58.png)

**Note**. The tests are done using the `develop` branch (skrl version 0.8.0, unreleased) with introduces some breaking changes in the way models are defined (visit `develop` documentation for more details https://skrl.readthedocs.io/en/develop/intro/installation.html#changelog)

**Comment by Wjzsearcher** [comment]
Hi, @Toni-SM 
Thanks for the quick response!
I was surprised that the initialization strategy would matter so much! Moreover, I can keep going with this wonderful library.
Thank you!
