### ISSUE TITLE
(docs) Add example with image input e.g. OpenAI Atari and a CNN policy

### ISSUE THREAD

**Issue by simonbogh** [Toni-SM/skrl#4]
Would be very useful with an example with image input e.g. OpenAI Atari and a CNN policy.

**Comment by Toni-SM** [comment]
Hi @simonbogh 

Version 0.3.0 has been released. It includes snippets (on each model class) for creating CNN and an example of its use in Isaac Sim's (2021.2.1) JetBot environment.
