### ISSUE TITLE
[Question] TD3_DEFAULT_CONFIG 

### ISSUE THREAD

**Issue by sjYoondeltar** [Toni-SM/skrl#55]
Hi @Toni-SM 

While utilizing TD3 agent on the pendulum-v1 env with the default config, I checked that "smooth_regularization_noise" is None in default config.

however, that cfg make this below error.

[skrl/agents/torch/td3/td3.py](https://localhost:8080/#) in _update(self, timestep, timesteps)
    393                 # target policy smoothing
    394                 next_actions, _, _ = self.target_policy.act({"states": sampled_next_states, **rnn_policy}, role="target_policy")
--> 395                 noises = torch.clamp(self._smooth_regularization_noise.sample(next_actions.shape),
    396                                      min=-self._smooth_regularization_clip,
    397                                      max=self._smooth_regularization_clip)

AttributeError: 'NoneType' object has no attribute 'sample'

I add the line `cfg_td3["smooth_regularization_noise"] = GaussianNoise(mean=0, std=1)` to avoid that error and it works.

Could you check this error and kindly let me know what would be a suitable default value for smooth_regularization_noise in TD3?

**Comment by Toni-SM** [comment]
Hi @sjYoondeltar 

I assume the regularization noise is always defined by the user for training. 
I will fix the implementation to ignore its use when it's `None` (and show a warning message in this case) 

A typical configuration can be found in the following example (`td3_gym_pendulum.py`):

https://github.com/Toni-SM/skrl/blob/b760dc7d49aad6b53a8ab2a81be704bb8a6f10dd/docs/source/examples/gym/td3_gym_pendulum.py#L87-L88

In this example, the parameters are the same as those used by the TD3 authors to evaluate the algorithm in the paper

![Screenshot from 2023-01-28 17-21-59](https://user-images.githubusercontent.com/22400377/215277479-aed8f171-0259-4be0-b8ad-5629299d634a.png)

**Comment by sjYoondeltar** [comment]
Thanks for your answering @Toni-SM

**Comment by Toni-SM** [comment]
Hi @sjYoondeltar 

Many thanks for reporting this issue.

A warning message has been added to the development version (`develop` branch) when the regularization noise is not specified and its availability is checked before applying it.

https://github.com/Toni-SM/skrl/blob/bca2173ed238cdead3024f67eba62acbd55bb545/skrl/agents/torch/td3/td3.py#L160-L161

https://github.com/Toni-SM/skrl/blob/bca2173ed238cdead3024f67eba62acbd55bb545/skrl/agents/torch/td3/td3.py#L357-L361
